// Simple language toggle: English default, French on click
const translations = {
    en: {
        'hero-title': 'Private Mobility, Redefined',
        'hero-subtitle': 'Discreet, elite luxury car rental and private mobility services in Morocco.',
        'cta-primary': 'Request via WhatsApp',
        'cta-secondary': 'View Fleet',
        'about-title': 'About',
        'about-text': 'Morocco Luxury Car delivers unparalleled private mobility solutions, tailored for discerning clients. With a commitment to discretion, security, and international standards, we provide access to elite vehicles and services across Marrakech, Casablanca, and key airports. Our approach ensures seamless experiences for the world\'s most elite travelers.',
        'fleet-title': 'Fleet',
        'executive-title': 'Executive',
        'executive-text': 'Refined sedans for professional journeys, embodying authority and comfort.',
        'luxury-title': 'Luxury',
        'luxury-text': 'Opulent SUVs and limousines, designed for distinguished travel.',
        'performance-title': 'Performance',
        'performance-text': 'High-performance vehicles for enthusiasts seeking exhilaration.',
        'elite-title': 'Elite',
        'elite-text': 'Exclusive models, reserved for the most discerning clientele.',
        'services-title': 'Services',
        'service-1': 'Airport VIP delivery and transfers',
        'service-2': 'Private chauffeur services',
        'service-3': 'Long-term luxury rental',
        'service-4': 'Events and special occasions',
        'service-5': 'Discretion and security protocols',
        'contact-title': 'Contact',
        'contact-text': 'For inquiries, reach us directly.',
        'contact-cta': 'Request via WhatsApp'
    },
    fr: {
        'hero-title': 'Mobilité Privée, Redéfinie',
        'hero-subtitle': 'Location de voitures de luxe discrète et d\'élite, et services de mobilité privée au Maroc.',
        'cta-primary': 'Demander via WhatsApp',
        'cta-secondary': 'Voir la Flotte',
        'about-title': 'À Propos',
        'about-text': 'Morocco Luxury Car offre des solutions de mobilité privée inégalées, adaptées aux clients exigeants. Avec un engagement envers la discrétion, la sécurité et les normes internationales, nous fournissons un accès aux véhicules et services d\'élite à Marrakech, Casablanca et aux aéroports clés. Notre approche garantit des expériences fluides pour les voyageurs les plus élites du monde.',
        'fleet-title': 'Flotte',
        'executive-title': 'Exécutif',
        'executive-text': 'Berlines raffinées pour les voyages professionnels, incarnant autorité et confort.',
        'luxury-title': 'Luxe',
        'luxury-text': 'SUV et limousines opulentes, conçues pour les voyages distingués.',
        'performance-title': 'Performance',
        'performance-text': 'Véhicules haute performance pour les passionnés cherchant l\'exaltation.',
        'elite-title': 'Élite',
        'elite-text': 'Modèles exclusifs, réservés à la clientèle la plus exigeante.',
